// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum CaptureApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Qué papel cumple este móvil en el soporte.
enum CameraRole: Int, CaseIterable {
  /// Cubre la mitad izquierda del campo. Es además el maestro del reloj: el otro
  /// móvil mide su desfase contra este (ADR 0012, decisión 2).
  case left = 0
  /// Cubre la mitad derecha y sigue el reloj de la izquierda.
  case right = 1
}

/// Estado térmico del dispositivo, copia de `ProcessInfo.ThermalState`.
///
/// No es telemetría decorativa: es la señal con la que se baja el bitrate antes de
/// que iOS decida bajarlo por su cuenta matando la sesión de captura.
enum ThermalState: Int, CaseIterable {
  case nominal = 0
  case fair = 1
  case serious = 2
  case critical = 3
}

/// Ajustes con los que se abre la cámara. Todos son decisiones del ADR 0012, no
/// preferencias: cambiarlos invalida la calibración del soporte.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CaptureSettings: Hashable, CustomStringConvertible {
  var role: CameraRole
  /// 3840×2160. El balón de 5–25 px no sobrevive a menos resolución (§9.2).
  var width: Int64
  var height: Int64
  /// Cadencia nominal. Las dos cámaras tienen que coincidir dentro de 0.5 Hz o el
  /// servidor rechaza el soporte (`RIG_MAX_FPS_MISMATCH_HZ`).
  var fps: Int64
  /// Tasa de bits del encoder HEVC. Fija, nunca adaptativa: los dos móviles comparten
  /// el enlace de Starlink y dos controles adaptativos se pelean entre sí.
  var bitrateBps: Int64
  /// Denominador de la obturación: 100 con red de 50 Hz, 120 con 60 Hz. Múltiplo de la
  /// frecuencia de red para que los focos del campo no produzcan bandas.
  var shutterDenominator: Int64
  /// ISO de reserva. La exposición se mide en automático al abrir la cámara y se
  /// congela trasladada a la obturación sin parpadeo; este valor solo se usa si la
  /// cámara no llega a medir nada. Igual en los dos móviles para que la costura no
  /// cambie de brillo; si los modelos son distintos, lo remata la corrección de
  /// ganancia del servidor.
  var iso: Int64
  /// Recorta verticalmente a la banda jugable antes de codificar (TASK A6). Ahorra un
  /// tercio del bitrate tirando cielo y grada, que no se usan para nada.
  var cropToPlayableBand: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureSettings? {
    let role = pigeonVar_list[0] as! CameraRole
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let fps = pigeonVar_list[3] as! Int64
    let bitrateBps = pigeonVar_list[4] as! Int64
    let shutterDenominator = pigeonVar_list[5] as! Int64
    let iso = pigeonVar_list[6] as! Int64
    let cropToPlayableBand = pigeonVar_list[7] as! Bool

    return CaptureSettings(
      role: role,
      width: width,
      height: height,
      fps: fps,
      bitrateBps: bitrateBps,
      shutterDenominator: shutterDenominator,
      iso: iso,
      cropToPlayableBand: cropToPlayableBand
    )
  }
  func toList() -> [Any?] {
    return [
      role,
      width,
      height,
      fps,
      bitrateBps,
      shutterDenominator,
      iso,
      cropToPlayableBand,
    ]
  }
  static func == (lhs: CaptureSettings, rhs: CaptureSettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CaptureApiPigeonInternal.deepEquals(lhs.role, rhs.role) && CaptureApiPigeonInternal.deepEquals(lhs.width, rhs.width) && CaptureApiPigeonInternal.deepEquals(lhs.height, rhs.height) && CaptureApiPigeonInternal.deepEquals(lhs.fps, rhs.fps) && CaptureApiPigeonInternal.deepEquals(lhs.bitrateBps, rhs.bitrateBps) && CaptureApiPigeonInternal.deepEquals(lhs.shutterDenominator, rhs.shutterDenominator) && CaptureApiPigeonInternal.deepEquals(lhs.iso, rhs.iso) && CaptureApiPigeonInternal.deepEquals(lhs.cropToPlayableBand, rhs.cropToPlayableBand)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureSettings")
    CaptureApiPigeonInternal.deepHash(value: role, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: fps, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: bitrateBps, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: shutterDenominator, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: iso, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: cropToPlayableBand, hasher: &hasher)
  }

  public var description: String {
    return "CaptureSettings(role: \(String(describing: role)), width: \(String(describing: width)), height: \(String(describing: height)), fps: \(String(describing: fps)), bitrateBps: \(String(describing: bitrateBps)), shutterDenominator: \(String(describing: shutterDenominator)), iso: \(String(describing: iso)), cropToPlayableBand: \(String(describing: cropToPlayableBand)))"
  }
}

/// Lo que la cámara consiguió aplicar de verdad.
///
/// Existe porque «pedirlo» y «tenerlo» no son lo mismo en AVFoundation: un formato
/// puede no admitir la combinación exacta de resolución y cadencia, y enterarse en la
/// cancha por la cara del vídeo no es una opción.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CaptureStatus: Hashable, CustomStringConvertible {
  var running: Bool
  var width: Int64
  var height: Int64
  var actualFps: Double
  /// `false` aquí invalida el soporte entero: con la estabilización activa el iPhone
  /// recorta y desplaza la imagen, y la rotación calibrada deja de valer.
  var stabilizationDisabled: Bool
  var exposureLocked: Bool
  /// Lo que quedó congelado: obturación en segundos e ISO. Se enseñan para que quien
  /// monta el soporte vea que los dos móviles miden lo mismo.
  var exposureSeconds: Double
  var iso: Int64
  var whiteBalanceLocked: Bool
  /// Temperatura de color congelada, en kelvin.
  var whiteBalanceKelvin: Int64
  var focusLocked: Bool
  /// La matriz intrínseca por frame. Sin ella hay que caer a `from_hfov`, que sirve
  /// para dimensionar y no para cerrar una costura.
  var intrinsicsAvailable: Bool
  var thermalState: ThermalState
  var batteryLevel: Double
  var freeDiskBytes: Int64
  var droppedFrames: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CaptureStatus? {
    let running = pigeonVar_list[0] as! Bool
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let actualFps = pigeonVar_list[3] as! Double
    let stabilizationDisabled = pigeonVar_list[4] as! Bool
    let exposureLocked = pigeonVar_list[5] as! Bool
    let exposureSeconds = pigeonVar_list[6] as! Double
    let iso = pigeonVar_list[7] as! Int64
    let whiteBalanceLocked = pigeonVar_list[8] as! Bool
    let whiteBalanceKelvin = pigeonVar_list[9] as! Int64
    let focusLocked = pigeonVar_list[10] as! Bool
    let intrinsicsAvailable = pigeonVar_list[11] as! Bool
    let thermalState = pigeonVar_list[12] as! ThermalState
    let batteryLevel = pigeonVar_list[13] as! Double
    let freeDiskBytes = pigeonVar_list[14] as! Int64
    let droppedFrames = pigeonVar_list[15] as! Int64

    return CaptureStatus(
      running: running,
      width: width,
      height: height,
      actualFps: actualFps,
      stabilizationDisabled: stabilizationDisabled,
      exposureLocked: exposureLocked,
      exposureSeconds: exposureSeconds,
      iso: iso,
      whiteBalanceLocked: whiteBalanceLocked,
      whiteBalanceKelvin: whiteBalanceKelvin,
      focusLocked: focusLocked,
      intrinsicsAvailable: intrinsicsAvailable,
      thermalState: thermalState,
      batteryLevel: batteryLevel,
      freeDiskBytes: freeDiskBytes,
      droppedFrames: droppedFrames
    )
  }
  func toList() -> [Any?] {
    return [
      running,
      width,
      height,
      actualFps,
      stabilizationDisabled,
      exposureLocked,
      exposureSeconds,
      iso,
      whiteBalanceLocked,
      whiteBalanceKelvin,
      focusLocked,
      intrinsicsAvailable,
      thermalState,
      batteryLevel,
      freeDiskBytes,
      droppedFrames,
    ]
  }
  static func == (lhs: CaptureStatus, rhs: CaptureStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CaptureApiPigeonInternal.deepEquals(lhs.running, rhs.running) && CaptureApiPigeonInternal.deepEquals(lhs.width, rhs.width) && CaptureApiPigeonInternal.deepEquals(lhs.height, rhs.height) && CaptureApiPigeonInternal.deepEquals(lhs.actualFps, rhs.actualFps) && CaptureApiPigeonInternal.deepEquals(lhs.stabilizationDisabled, rhs.stabilizationDisabled) && CaptureApiPigeonInternal.deepEquals(lhs.exposureLocked, rhs.exposureLocked) && CaptureApiPigeonInternal.deepEquals(lhs.exposureSeconds, rhs.exposureSeconds) && CaptureApiPigeonInternal.deepEquals(lhs.iso, rhs.iso) && CaptureApiPigeonInternal.deepEquals(lhs.whiteBalanceLocked, rhs.whiteBalanceLocked) && CaptureApiPigeonInternal.deepEquals(lhs.whiteBalanceKelvin, rhs.whiteBalanceKelvin) && CaptureApiPigeonInternal.deepEquals(lhs.focusLocked, rhs.focusLocked) && CaptureApiPigeonInternal.deepEquals(lhs.intrinsicsAvailable, rhs.intrinsicsAvailable) && CaptureApiPigeonInternal.deepEquals(lhs.thermalState, rhs.thermalState) && CaptureApiPigeonInternal.deepEquals(lhs.batteryLevel, rhs.batteryLevel) && CaptureApiPigeonInternal.deepEquals(lhs.freeDiskBytes, rhs.freeDiskBytes) && CaptureApiPigeonInternal.deepEquals(lhs.droppedFrames, rhs.droppedFrames)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CaptureStatus")
    CaptureApiPigeonInternal.deepHash(value: running, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: actualFps, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: stabilizationDisabled, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: exposureLocked, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: exposureSeconds, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: iso, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: whiteBalanceLocked, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: whiteBalanceKelvin, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: focusLocked, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: intrinsicsAvailable, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: thermalState, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: batteryLevel, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: freeDiskBytes, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: droppedFrames, hasher: &hasher)
  }

  public var description: String {
    return "CaptureStatus(running: \(String(describing: running)), width: \(String(describing: width)), height: \(String(describing: height)), actualFps: \(String(describing: actualFps)), stabilizationDisabled: \(String(describing: stabilizationDisabled)), exposureLocked: \(String(describing: exposureLocked)), exposureSeconds: \(String(describing: exposureSeconds)), iso: \(String(describing: iso)), whiteBalanceLocked: \(String(describing: whiteBalanceLocked)), whiteBalanceKelvin: \(String(describing: whiteBalanceKelvin)), focusLocked: \(String(describing: focusLocked)), intrinsicsAvailable: \(String(describing: intrinsicsAvailable)), thermalState: \(String(describing: thermalState)), batteryLevel: \(String(describing: batteryLevel)), freeDiskBytes: \(String(describing: freeDiskBytes)), droppedFrames: \(String(describing: droppedFrames)))"
  }
}

/// Una medida de desfase entre este móvil y el maestro del reloj.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ClockSample: Hashable, CustomStringConvertible {
  /// Ida y vuelta de la medida. Se conserva porque es lo que decide si la muestra
  /// vale: con jitter de WiFi, solo las de RTT mínimo dan un offset creíble.
  var roundTripNs: Int64
  /// Desfase estimado: cuánto hay que sumar al reloj local para obtener el del maestro.
  var offsetNs: Int64
  var localMonotonicNs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClockSample? {
    let roundTripNs = pigeonVar_list[0] as! Int64
    let offsetNs = pigeonVar_list[1] as! Int64
    let localMonotonicNs = pigeonVar_list[2] as! Int64

    return ClockSample(
      roundTripNs: roundTripNs,
      offsetNs: offsetNs,
      localMonotonicNs: localMonotonicNs
    )
  }
  func toList() -> [Any?] {
    return [
      roundTripNs,
      offsetNs,
      localMonotonicNs,
    ]
  }
  static func == (lhs: ClockSample, rhs: ClockSample) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CaptureApiPigeonInternal.deepEquals(lhs.roundTripNs, rhs.roundTripNs) && CaptureApiPigeonInternal.deepEquals(lhs.offsetNs, rhs.offsetNs) && CaptureApiPigeonInternal.deepEquals(lhs.localMonotonicNs, rhs.localMonotonicNs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClockSample")
    CaptureApiPigeonInternal.deepHash(value: roundTripNs, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: offsetNs, hasher: &hasher)
    CaptureApiPigeonInternal.deepHash(value: localMonotonicNs, hasher: &hasher)
  }

  public var description: String {
    return "ClockSample(roundTripNs: \(String(describing: roundTripNs)), offsetNs: \(String(describing: offsetNs)), localMonotonicNs: \(String(describing: localMonotonicNs)))"
  }
}

private class CaptureApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraRole(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return CaptureSettings.fromList(self.readValue() as! [Any?])
    case 132:
      return CaptureStatus.fromList(self.readValue() as! [Any?])
    case 133:
      return ClockSample.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CaptureApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraRole {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ThermalState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CaptureSettings {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CaptureStatus {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ClockSample {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CaptureApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CaptureApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CaptureApiPigeonCodecWriter(data: data)
  }
}

class CaptureApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CaptureApiPigeonCodec(readerWriter: CaptureApiPigeonCodecReaderWriter())
}


/// La cámara nativa. Todo lo que Flutter no puede hacer por sí mismo.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CaptureHostApi {
  /// Pide al sistema el permiso de cámara y espera la respuesta.
  ///
  /// Va antes que cualquier otra llamada: sin permiso, AVFoundation acepta abrir la
  /// sesión y no entrega ni un frame, sin error. Es asíncrono porque el diálogo de iOS
  /// lo es: la respuesta llega cuando el operador pulsa.
  func requestCameraAccess() async throws -> Bool
  /// `true` si este iPhone tiene ultra gran angular.
  ///
  /// Se resuelve con `AVCaptureDevice.DiscoverySession`, **nunca con una lista de
  /// modelos**: Veo Go rechazó el iPhone 17 Pro por tener una lista desactualizada.
  func hasUltraWideCamera() throws -> Bool
  /// Abre la cámara con los ajustes dados y devuelve lo que se aplicó de verdad.
  ///
  /// Tarda unos segundos: la cámara mide exposición y balance en automático antes de
  /// congelarlos, y no se responde hasta que estén congelados.
  func configure(settings: CaptureSettings) async throws -> CaptureStatus
  /// Empieza a grabar en local y a emitir por SRT. La grabación local no es opcional:
  /// es lo que convierte un fallo de red en un partido en diferido (ADR 0012, dec. 5).
  ///
  /// Devuelve la ruta del archivo que se está escribiendo: la pantalla lo enseña, y
  /// quien lo busque después en Finder sabe cuál es.
  func start(srtUrl: String, recordingDirectory: String) throws -> String
  func stop() throws
  func status() throws -> CaptureStatus
  /// PTS de los últimos frames capturados, ya en tiempo del soporte (TASK A4).
  ///
  /// El nativo no puede calcular la fase de exposición él solo: la fase es un desfase
  /// **entre los dos móviles**, y cada uno solo conoce sus propios sellos. Así que
  /// entrega los suyos y la resta se hace en Dart, que es quien tiene el enlace con el
  /// otro móvil (`measurePhaseNs`).
  func recentFramePtsNs() throws -> [Int64]
  /// Reabre la sesión para volver a sortear la fase.
  func restartForPhase() throws
  /// Fija el desfase de reloj que se aplicará a los PTS emitidos. Es lo que pone los
  /// dos streams en el dominio de tiempo del soporte (ADR 0012, decisión 2).
  func setClockOffsetNs(offsetNs: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CaptureHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CaptureApiPigeonCodec.shared }
  /// Sets up an instance of `CaptureHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CaptureHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Pide al sistema el permiso de cámara y espera la respuesta.
    ///
    /// Va antes que cualquier otra llamada: sin permiso, AVFoundation acepta abrir la
    /// sesión y no entrega ni un frame, sin error. Es asíncrono porque el diálogo de iOS
    /// lo es: la respuesta llega cuando el operador pulsa.
    let requestCameraAccessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.requestCameraAccess\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCameraAccessChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestCameraAccess()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCameraAccessChannel.setMessageHandler(nil)
    }
    /// `true` si este iPhone tiene ultra gran angular.
    ///
    /// Se resuelve con `AVCaptureDevice.DiscoverySession`, **nunca con una lista de
    /// modelos**: Veo Go rechazó el iPhone 17 Pro por tener una lista desactualizada.
    let hasUltraWideCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.hasUltraWideCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasUltraWideCameraChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasUltraWideCamera()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasUltraWideCameraChannel.setMessageHandler(nil)
    }
    /// Abre la cámara con los ajustes dados y devuelve lo que se aplicó de verdad.
    ///
    /// Tarda unos segundos: la cámara mide exposición y balance en automático antes de
    /// congelarlos, y no se responde hasta que estén congelados.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! CaptureSettings
        Task { @MainActor in
          do {
            let result = try await api.configure(settings: settingsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// Empieza a grabar en local y a emitir por SRT. La grabación local no es opcional:
    /// es lo que convierte un fallo de red en un partido en diferido (ADR 0012, dec. 5).
    ///
    /// Devuelve la ruta del archivo que se está escribiendo: la pantalla lo enseña, y
    /// quien lo busque después en Finder sabe cuál es.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let srtUrlArg = args[0] as! String
        let recordingDirectoryArg = args[1] as! String
        do {
          let result = try api.start(srtUrl: srtUrlArg, recordingDirectory: recordingDirectoryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let statusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.status\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      statusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.status()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      statusChannel.setMessageHandler(nil)
    }
    /// PTS de los últimos frames capturados, ya en tiempo del soporte (TASK A4).
    ///
    /// El nativo no puede calcular la fase de exposición él solo: la fase es un desfase
    /// **entre los dos móviles**, y cada uno solo conoce sus propios sellos. Así que
    /// entrega los suyos y la resta se hace en Dart, que es quien tiene el enlace con el
    /// otro móvil (`measurePhaseNs`).
    let recentFramePtsNsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.recentFramePtsNs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recentFramePtsNsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.recentFramePtsNs()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      recentFramePtsNsChannel.setMessageHandler(nil)
    }
    /// Reabre la sesión para volver a sortear la fase.
    let restartForPhaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.restartForPhase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restartForPhaseChannel.setMessageHandler { _, reply in
        do {
          try api.restartForPhase()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      restartForPhaseChannel.setMessageHandler(nil)
    }
    /// Fija el desfase de reloj que se aplicará a los PTS emitidos. Es lo que pone los
    /// dos streams en el dominio de tiempo del soporte (ADR 0012, decisión 2).
    let setClockOffsetNsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.CaptureHostApi.setClockOffsetNs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setClockOffsetNsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let offsetNsArg = args[0] as! Int64
        do {
          try api.setClockOffsetNs(offsetNs: offsetNsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setClockOffsetNsChannel.setMessageHandler(nil)
    }
  }
}

/// Avisos que el nativo empuja hacia Flutter sin que nadie pregunte.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CaptureFlutterApiProtocol {
  /// La sesión se interrumpió (llamada entrante, otra app tomó la cámara, calor).
  /// Tras esto la grabación continúa en un segmento nuevo.
  @MainActor func onInterrupted(reason reasonArg: String) async throws
  @MainActor func onResumed() async throws
  /// Cambio de estado térmico. Por encima de `serious` hay que bajar el bitrate.
  @MainActor func onThermalStateChanged(state stateArg: ThermalState) async throws
  @MainActor func onStatus(status statusArg: CaptureStatus) async throws
}
class CaptureFlutterApi: CaptureFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CaptureApiPigeonCodec {
    return CaptureApiPigeonCodec.shared
  }
  /// La sesión se interrumpió (llamada entrante, otra app tomó la cámara, calor).
  /// Tras esto la grabación continúa en un segmento nuevo.
  @MainActor func onInterrupted(reason reasonArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.football_ai_capture.CaptureFlutterApi.onInterrupted\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([reasonArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onResumed() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.football_ai_capture.CaptureFlutterApi.onResumed\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// Cambio de estado térmico. Por encima de `serious` hay que bajar el bitrate.
  @MainActor func onThermalStateChanged(state stateArg: ThermalState) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.football_ai_capture.CaptureFlutterApi.onThermalStateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onStatus(status statusArg: CaptureStatus) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.football_ai_capture.CaptureFlutterApi.onStatus\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([statusArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
