// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum RigApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class RigApiPigeonCodecReader: FlutterStandardReader {
}

private class RigApiPigeonCodecWriter: FlutterStandardWriter {
}

private class RigApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RigApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RigApiPigeonCodecWriter(data: data)
  }
}

class RigApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RigApiPigeonCodec(readerWriter: RigApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RigHostApi {
  /// Lanza un banco por nombre (IOS-08) y devuelve la ruta del informe JSON que dejó
  /// en Documents/bench/. `paramsJson` son los parámetros del banco, tal cual se
  /// guardan en el informe; `{}` si no hay.
  ///
  /// Es la prueba de una sola acción: `flutter run --dart-define=BENCH=<nombre>`
  /// arranca, corre y escribe, sin tocar la pantalla.
  func runBench(name: String, paramsJson: String) async throws -> String
  /// Una capa del gráfico del programa (IOS-47): RGBA sin premultiplicar de
  /// `width × height`, ya recortada a su caja con contenido, en (`x`, `y`) del programa.
  /// `layer`: 0 marcador, 1 alineación, 2 SIN SEÑAL. Una `generation` que no sube se
  /// ignora en nativo.
  func setOverlay(rgba: FlutterStandardTypedData, width: Int64, height: Int64, x: Int64, y: Int64, layer: Int64, generation: Int64) throws
  /// Quita una capa del gráfico.
  func clearOverlay(layer: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RigHostApiSetup {
  static var codec: FlutterStandardMessageCodec { RigApiPigeonCodec.shared }
  /// Sets up an instance of `RigHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RigHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Lanza un banco por nombre (IOS-08) y devuelve la ruta del informe JSON que dejó
    /// en Documents/bench/. `paramsJson` son los parámetros del banco, tal cual se
    /// guardan en el informe; `{}` si no hay.
    ///
    /// Es la prueba de una sola acción: `flutter run --dart-define=BENCH=<nombre>`
    /// arranca, corre y escribe, sin tocar la pantalla.
    let runBenchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.RigHostApi.runBench\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runBenchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let paramsJsonArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.runBench(name: nameArg, paramsJson: paramsJsonArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      runBenchChannel.setMessageHandler(nil)
    }
    /// Una capa del gráfico del programa (IOS-47): RGBA sin premultiplicar de
    /// `width × height`, ya recortada a su caja con contenido, en (`x`, `y`) del programa.
    /// `layer`: 0 marcador, 1 alineación, 2 SIN SEÑAL. Una `generation` que no sube se
    /// ignora en nativo.
    let setOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.RigHostApi.setOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rgbaArg = args[0] as! FlutterStandardTypedData
        let widthArg = args[1] as! Int64
        let heightArg = args[2] as! Int64
        let xArg = args[3] as! Int64
        let yArg = args[4] as! Int64
        let layerArg = args[5] as! Int64
        let generationArg = args[6] as! Int64
        do {
          try api.setOverlay(rgba: rgbaArg, width: widthArg, height: heightArg, x: xArg, y: yArg, layer: layerArg, generation: generationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOverlayChannel.setMessageHandler(nil)
    }
    /// Quita una capa del gráfico.
    let clearOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.football_ai_capture.RigHostApi.clearOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let layerArg = args[0] as! Int64
        do {
          try api.clearOverlay(layer: layerArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearOverlayChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol RigFlutterApiProtocol {
  /// Progreso del banco en marcha, para la página: fracción 0-1 y una línea de detalle.
  @MainActor func onBenchProgress(name nameArg: String, fraction fractionArg: Double, detail detailArg: String) async throws
}
class RigFlutterApi: RigFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: RigApiPigeonCodec {
    return RigApiPigeonCodec.shared
  }
  /// Progreso del banco en marcha, para la página: fracción 0-1 y una línea de detalle.
  @MainActor func onBenchProgress(name nameArg: String, fraction fractionArg: Double, detail detailArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.football_ai_capture.RigFlutterApi.onBenchProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([nameArg, fractionArg, detailArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
